### ISSUE TITLE
Image resolution too small on large screen

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/unsplash#102]
The url can specify the current screen size like this
https://source.unsplash.com/featured/2560x1440?nature,nature

![image](https://source.unsplash.com/featured/2560x1440?nature,nature)

We should use that

**Comment by newhinton** [comment]
@skjnldsv Yes and no. It would be great if we can add this via css, but we cannot provide this by default (at the moment).
Especially since i am preparing a bigger release with many more sources for images. We already can select keywords, but not modify the url directly (as to prevent abuse)

Check out the dev-branch, it has a HD version for the url. Review is appreciated ;)

**Comment by skjnldsv** [comment]
You can provide the url via javascript and css variables `--image-background` https://github.com/nextcloud/server/blob/07c9bf1adff8a2d10ff774da32c2ddd54fd01923/apps/theming/lib/Themes/DefaultTheme.php#L191-L203
https://stackoverflow.com/a/55270268/3885878

**Comment by newhinton** [comment]
I would like to not use js for this, i think the solution i have now is quite elegant. 

I will rethink this at a later point, but i think it would be more useful if i would implement better customization for the provider in the dev branch. That would solve this issue aswell, as long as the webbrowser does not influence the loaded images. 

It would be kinda awesome if the webbrowser would edit the size, to load a perfectly fitting image. However, i dont see how we could implement that for different image provider like wikimedia, or wallhaven.cc

**Comment by skjnldsv** [comment]
We could also load a bigger image.
Honestly, pixelized login screen looks kinda bad :/

**Comment by skjnldsv** [comment]
Oh, I have an idea, we could use media queries!
```css
@media only screen and (max-width: 1080px) {
	  body#body-login {
	      background-image: url('https://source.unsplash.com/featured/1920x1080?nature,nature') !important;
	}
}

@media only screen and (max-width: 2560px) {
	  body#body-login {
	      background-image: url('https://source.unsplash.com/featured/2560x1440?nature,nature') !important;
	}
}

@media only screen and (max-width: 3840px) {
	  body#body-login {
	      background-image: url('https://source.unsplash.com/featured/3840x2160?nature,nature') !important;
	}
}

```
